version: '3.8'

name: ryokan
services:
  db:
    image: postgres:16.2
    ports:
      - 5436:5432
    environment:
      POSTGRES_DB: condor
      POSTGRES_USER: condor
      POSTGRES_PASSWORD: t0p_secret
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
